#!/bin/sh

set -x
set -e

sudo apt-get install tar wget jq

# Stick to stable release
VERSION="0.13.0"
ZIG="zig-linux-x86_64-$VERSION"

wget -nv "https://ziglang.org/builds/$ZIG.tar.xz"
tar xf "$ZIG.tar.xz"
export PATH="$(pwd)/$ZIG:$PATH"

# Main
zig build

