#!/bin/sh

set -x
set -e

# Stick to stable release
VERSION="0.13.0"
ZIG="zig-windows-x86_64-$VERSION"

curl -L "https://ziglang.org/builds/$ZIG.zip" -o "$ZIG.zip"
7z x "$ZIG.zip"
export PATH="$(pwd)/$ZIG:$PATH"

# Main
zig build

