#!/bin/sh

set -x
set -e

# Always use zig master
curl -L http://ziglang.org/download/index.json -o index.json
ZIG="zig-windows-x86_64-$(cat index.json | jq -r .master.version)"

curl -L "https://ziglang.org/builds/$ZIG.zip" -o "$ZIG.zip"
7z x "$ZIG.zip"
export PATH="$(pwd)/$ZIG:$PATH"

# Gyro does not need to be updated much often
GYRO_VER="0.5.0"
GYRO="gyro-$GYRO_VER-windows-x86_64"
curl -L "http://github.com/mattnite/gyro/releases/download/$GYRO_VER/$GYRO.zip" -o "$GYRO.zip"
7z x "$GYRO.zip"
export PATH="$(pwd)/$GYRO/bin:$PATH"

# Main
gyro fetch
zig build

